---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions 
summary: A disposição em camadas do BlueXP  é compatível com duas categorias de acesso e a maioria das regiões. 
---
= Camadas e regiões de acesso Blob do Azure compatíveis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A disposição em camadas do BlueXP  é compatível com duas categorias de acesso e a maioria das regiões.



== Camadas de acesso Azure Blob compatíveis

Quando você configura a disposição de dados em categorias no Azure a partir de seus sistemas ONTAP locais, a disposição em camadas do BlueXP  usa automaticamente o nível _Hot_ Access para seus dados inativos. A disposição em camadas do BlueXP  pode aplicar uma regra de ciclo de vida para que os dados transitem do nível de acesso _quente_ para o nível de acesso _frio_ depois de um determinado número de dias.

Se você não escolher o nível de acesso _Cool_, os dados permanecerão no nível de acesso _Hot_ e nenhuma regra será aplicada.

Quando você configura uma regra de ciclo de vida em camadas do BlueXP , não deve configurar nenhuma regra de ciclo de vida ao configurar o contêiner em sua conta do Azure.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Saiba mais sobre os níveis de acesso ao Blob do Azure"^].



== Regiões Azure compatíveis

O BlueXP  Tiering é compatível com as seguintes regiões do Azure. As regiões do Azure China não são compatíveis como destinos para disposição em camadas.



=== África

* África do Sul Norte




=== Ásia-Pacífico

* Leste da Austrália
* Sudeste da Austrália
* Leste da Ásia
* Leste do Japão
* Oeste do Japão
* Coreia Central
* Coreia do Sul
* Sudeste da Ásia




=== Europa

* França Central
* Alemanha Central Ocidental
* Alemanha Norte
* Norte da Europa
* Sul do Reino Unido
* Oeste do Reino Unido
* Europa Ocidental




=== América do Norte

* Canadá Central
* Leste do Canadá
* Central US
* Leste dos EUA
* East US 2
* North Central US
* South Central US
* Oeste dos EUA
* West US 2
* West Central US




=== América do Sul

* Brasil Sul

