---
sidebar: sidebar 
permalink: reference-google-support.html 
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive 
summary: O BlueXP  Tiering é compatível com várias classes de storage do Google Cloud e a maioria das regiões. 
---
= Regiões e classes de armazenamento do Google Cloud compatíveis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O BlueXP  Tiering é compatível com várias classes de storage do Google Cloud e a maioria das regiões.



== Classes de armazenamento do GCP compatíveis

Quando você configura a disposição de dados em categorias no GCP a partir dos sistemas ONTAP locais, a disposição em camadas do BlueXP  usa automaticamente a classe de storage _padrão_ para os dados inativos. A disposição em camadas do BlueXP  pode aplicar uma regra de ciclo de vida para que os dados transitem da classe de storage _padrão_ para outras classes de storage depois de um certo número de dias. Você pode escolher entre as seguintes classes de armazenamento:

* Nearline
* Coldline
* Arquivar


Se você não escolher outra classe de armazenamento, os dados permanecerão na classe de armazenamento _Standard_ e nenhuma regra será aplicada.

Quando você configura uma regra de ciclo de vida de disposição em camadas do BlueXP , não deve configurar nenhuma regra de ciclo de vida ao configurar o bucket na sua conta do Google.

https://cloud.google.com/storage/docs/storage-classes["Saiba mais sobre as aulas do Google Cloud Storage"^].



== Regiões compatíveis do Google Cloud

O BlueXP  Tiering é compatível com as seguintes regiões.



=== Américas

* Iowa
* Los Angeles
* Montreal
* N. Virginia
* Oregon
* Sao Paulo
* Carolina do Sul




=== Ásia-Pacífico

* Hong Kong
* Mumbai
* Osaka
* Singapura
* Sydney
* Taiwan
* Tóquio




=== Europa

* Bélgica
* Finlândia
* Frankfurt
* Londres
* Países Baixos
* Zurique

