---
sidebar: sidebar 
permalink: reference-google-support.html 
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive 
summary: O BlueXP  Tiering é compatível com várias classes de storage do Google Cloud e a maioria das regiões. 
---
= Regiões e classes de armazenamento do Google Cloud compatíveis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O BlueXP  Tiering é compatível com várias classes de storage do Google Cloud e a maioria das regiões.



== Classes de armazenamento do GCP compatíveis

Ao configurar o armazenamento em camadas de dados no Google Cloud a partir dos seus sistemas ONTAP locais, o armazenamento em camadas usa automaticamente a classe de armazenamento _Standard_ para seus dados inativos. O armazenamento em camadas pode aplicar uma regra de ciclo de vida para que os dados transitem da classe de armazenamento _Standard_ para outras classes de armazenamento após um determinado número de dias. Você pode escolher entre as seguintes classes de armazenamento:

* Nearline
* Coldline
* Arquivar


Se você não escolher outra classe de armazenamento, os dados permanecerão na classe de armazenamento _Standard_ e nenhuma regra será aplicada.

Ao configurar uma regra de ciclo de vida em camadas, você não deve configurar nenhuma regra de ciclo de vida ao configurar o bucket na sua conta do Google.

https://cloud.google.com/storage/docs/storage-classes["Saiba mais sobre as aulas do Google Cloud Storage"^].



== Regiões compatíveis do Google Cloud

A hierarquização oferece suporte às seguintes regiões.



=== Américas

* Iowa
* Los Angeles
* Montreal
* N. Virginia
* Oregon
* Sao Paulo
* Carolina do Sul




=== Ásia-Pacífico

* Hong Kong
* Mumbai
* Osaka
* Singapura
* Sydney
* Taiwan
* Tóquio




=== Europa

* Bélgica
* Finlândia
* Frankfurt
* Londres
* Países Baixos
* Zurique

